version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - "16686:16686" # Web UI
      - "6832:6831/udp" # Jaeger agent

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ZakirAghakisyev1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
      - "6831:6831/udp"
    networks:
      - appnet

  orderapp:
    image: orderappimage   
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=OrderApp;User Id=sa;Password=ZakirAghakisyev1234;TrustServerCertificate=true"
    ports:
      - "5000:8080"
    networks:
      - appnet
    volumes:
      - "C:/Users/zakir/AppData/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro"

networks:
  appnet:
